note

diff --git a/.local/bin/scripts/fontpreview b/.local/bin/scripts/fontpreview
--- a/.local/bin/scripts/fontpreview
+++ b/.local/bin/scripts/fontpreview
@@ -1,8 +1,8 @@
-#!/usr/bin/env sh
-#
+#!/bin/sh
+
 # Siddharth Dushantha 2020
 #
-# Dependencies: sxiv, imagemagick, xdotool, fzf
+# Dependencies: nsxiv, imagemagick, xdotool, fzf
 
 FONT_PREVIEW="/tmp/font.png"
 VERSION=1.0.0
@@ -41,7 +41,7 @@ show_help() {
 pre_exit() {
     # Get the proccess ID of this script and kill it.
     # We are dumping the output of kill to /dev/null
-    # because if the user quits sxiv before they
+    # because if the user quits nsxiv before they
     # exit this script, an error will be shown
     # from kill and we dont want that
     kill -9 "$(cat /tmp/fontpreview.pid 2>/dev/null)" &> /dev/null
@@ -65,8 +65,8 @@ main(){
         echo "error: Could not find 'xdotool', is it installed?"
         return
     }
-    type -p sxiv &>/dev/null || {
-        echo "error: Could not find 'sxiv', is it installed?"
+    type -p nsxiv &>/dev/null || {
+        echo "error: Could not find 'nsxiv', is it installed?"
         return
     }
     type -p convert &>/dev/null || {
@@ -87,7 +87,7 @@ main(){
     [[ $FONTPREVIEW_PREVIEW_TEXT != "" ]] && PREVIEW_TEXT=$FONTPREVIEW_PREVIEW_TEXT
 
     # Save the window ID of the terminal window fontpreview is executed in.
-    # This is so that when we open up sxiv, we can change the focus back to
+    # This is so that when we open up nsxiv, we can change the focus back to
     # the terminal window, so that the user can search for the fonts without
     # having to manualy change the focus back to the terminal.
     xdotool getactivewindow > /tmp/terminal_window_id
@@ -109,23 +109,23 @@ main(){
         if [ $FIRST_RUN == true ]; then
             FIRST_RUN=false
 
-            # Display the font preview using sxiv
-            sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &
+            # Display the font preview using nsxiv
+            nsxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &
 
-            # Change focus from sxiv, back to the terminal window
+            # Change focus from nsxiv, back to the terminal window
             # so that user can continue to search for fonts without
             # having to manually change focus back to the terminal window
             xdotool windowfocus "$(cat /tmp/terminal_window_id)"
 
             # Save the process ID so that we can kill
-            # sxiv when the user exits the script
+            # nsxiv when the user exits the script
             echo $! >/tmp/fontpreview.pid
     	fi
     done
 }
 
 # Disable CTRL-Z because if we allowed this key press,
-# then the script would exit but, sxiv would still be
+# then the script would exit but, nsxiv would still be
 # running
 trap "" SIGTSTP
 
